apiVersion: apps/v1 # Which Kubernetes API Should this k8s Manifest file should use
# v1 or apps/v1
#
kind: Deployment
metadata:
  name: broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broker
  template:
    metadata:
      labels:
        app: broker
    spec:
      containers:
      - name: broker
        image: "kunalsin9h/broker-service:latest"
        ports:
          - containerPort: 5001
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"


---

apiVersion: v1
kind: Service
metadata:
  name: broker
spec:
  selector:
    app: broker
  ports:
    - protocol: TCP
      name: main-port
      port: 5001
      targetPort: 5001
