apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-dep
  template:
    metadata:
      labels:
        app: mongo-dep
    spec:
      containers:
      - name: mongo
        image: "mongo:latest"
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: "admin"
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: "admin"
          - name: MONGO_INITDB_DATABASE
            value: "logs"
        ports:
          - containerPort: 27017
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"


---

apiVersion: v1
kind: Service
metadata:
  name: mongo-dep
spec:
  selector:
    name: mongo-dep
  ports:
    - protocol: TCP
      name: main-port
      port: 27017
      targetPort: 27017