apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq-dep
  template:
    metadata:
      labels:
        app: rabbitmq-dep
    spec:
      containers:
      - name: rabbit
        image: "rabbitmq:3.11-alpine"
        ports:
          - containerPort: 5672
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"


---

apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-dep
spec:
  selector:
    name: rabbitmq-dep
  ports:
    - protocol: TCP
      name: main-port
      port: 5672
      targetPort: 5672