version: '3'
services:

  frontend:
    build:
      context: ./../frontend
      dockerfile: ./../frontend/frontend.dockerfile
    restart: always
    ports:
      - "5000:5000"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      BROKER_URL: "http://backend"

  broker:
    build:
      context: ./../broker
      dockerfile: ./../broker/broker.dockerfile
    restart: always
    ports:
      - "5001:5001"
    deploy:
      mode: replicated
      replicas: 1

  auth:
    build:
      context: ./../auth
      dockerfile: ./../auth/auth.dockerfile
    restart: always
    ports:
      - "5002:5002"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DSN: "postgres://admin:admin@postgres:5432/users"
    depends_on:
      - postgres

  postgres:
    image: 'postgres:14.6-alpine3.17'
    ports:
      - "5432:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: users
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/

  logger:
    build:
      context: ./../logger
      dockerfile: ./../logger/logger.dockerfile
    restart: always # like PM2 restarting the app on crash
    deploy:
      mode: replicated
      replicas: 1

  mongo:
    image: 'mongo:latest'
    ports:
      - "27017:27017"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: logs
    volumes:
      - ./db-data/mongo/:/data/db/

  mailhog:
    image: "lytrax/mailhog:latest"
    ports:
      - "1025:1025" # Mail Service [SMTP]
      - "8025:8025" # Web App

  mail:
    build:
      context: "./../mail"
      dockerfile: "./../mail/mail.dockerfile"
    ports:
      - "5004:5004"
    restart: "always"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      MAIL_DOMAIN: "localhost"
      MAIL_HOST: mailhog
      MAIL_PORT: 1025
      MAIL_USERNAME: ""
      MAIL_PASSWORD: ""
      MAIL_ENCRYPTION: "none"
      MAIL_FROM_NAME: "Kunal Singh"
      MAIL_FROM_ADDRESS: "kunal@knl.sh"
    depends_on:
      - mailhog

  listener:
    build:
      context: "./../listener"
      dockerfile: "./../listener/listener.dockerfile"
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - rabbitmq

  rabbitmq:
    image: "rabbitmq:3.11-management-alpine"
    ports:
      - "5672:5672" # AMQP Service
      - "15672:15672" # Management Webapp
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - ./db-data/rabbitmq/:/var/lib/rabbitmq/
