version: '3'
services:
  broker:
    build:
      context: ./../broker
      dockerfile: ./../broker/broker.dockerfile
    restart: always
    ports:
      - "5001:5001"
    deploy:
      mode: replicated
      replicas: 1
