
version: '3'

services:

  caddy:
    image: kunalsin9h/caddy-service:latest
    ports:
      - "80:80"
      - "443:443"
    deploy:
      mode: replicated
      replicas: 1
      placement: # These have dependency on host machine so they should not replicated on other nodes
        constraints:
          - node.hostname == node-001
    volumes:
      - caddy_data:/data
      - caddy_config:/config

  frontend:
    image: kunalsin9h/frontend-service:latest
    deploy:
      mode: replicated
      replicas: 1
    environment:
      BROKER_URL: "https://broker.kunalsin9h.dev"

  broker:
    image: kunalsin9h/broker-service:latest
    deploy:
      mode: replicated
      replicas: 1

  listener:
    image: kunalsin9h/listener-service
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == node-001
  auth:
    image: kunalsin9h/auth-service
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DSN: "postgres://admin:admin@postgres:5432/users"

  logger:
    image: kunalsin9h/logger-service
    deploy:
      mode: replicated
      replicas: 1

  mail:
    image:  kunalsin9h/mail-service
    deploy:
      mode: replicated
      replicas: 1
    environment:
      MAIL_DOMAIN: "localhost"
      MAIL_HOST: mailhog
      MAIL_PORT: 1025
      MAIL_USERNAME: ""
      MAIL_PASSWORD: ""
      MAIL_ENCRYPTION: "none"
      MAIL_FROM_NAME: "Kunal Singh"
      MAIL_FROM_ADDRESS: "kunal@knl.sh"

  rabbitmq:
    image: "rabbitmq:3.11-alpine"
    ports:
      - "5672:5672" # AMQP Service
    deploy:
      mode: replicated
      replicas: 1

  mailhog:
    image: "lytrax/mailhog:latest"
    ports:
      - "1025:1025" # Mail Service [SMTP]
    deploy:
      mode: replicated
      replicas: 1

  mongo:
    image: 'mongo:latest'
    ports:
      - "27017:27017"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == node-001
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: logs
    volumes:
      - ./db-data/mongo/:/data/db/

  postgres:
    image: 'postgres:14.6-alpine3.17'
    ports:
      - "5432:5432"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == node-001
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: users
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/

volumes:
  caddy_data:
    external: true
  caddy_config: