
version: '3'

services:

  frontend:
    image: kunalsin9h/frontend-services:latest
    deploy:
      mode: replicated
      replicas: 1

  broker:
    image: kunalsin9h/broker-service:latest
    deploy:
      mode: replicated
      replicas: 1

  listener:
    image: kunalsin9h/listener-service
    deploy:
      mode: replicated
      replicas: 1

  auth:
    image: kunalsin9h/auth-service
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DSN: "postgres://admin:admin@postgres:5432/users"

  logger:
    image: kunalsin9h/logger-service
    deploy:
      mode: replicated
      replicas: 1

  mail:
    image:  kunalsin9h/mail-service
    deploy:
      mode: replicated
      replicas: 1
    environment:
      MAIL_DOMAIN: "localhost"
      MAIL_HOST: mailhog
      MAIL_PORT: 1025
      MAIL_USERNAME: ""
      MAIL_PASSWORD: ""
      MAIL_ENCRYPTION: "none"
      MAIL_FROM_NAME: "Kunal Singh"
      MAIL_FROM_ADDRESS: "kunal@knl.sh"

  rabbitmq:
    image: "rabbitmq:3.11-alpine"
    deploy:
      mode: global # Only ever going to have one instance

  mailhog:
    image: "lytrax/mailhog:latest"
    deploy:
      mode: global

  mongo:
    image: 'mongo:latest'
    deploy:
      mode: global
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: logs
    volumes:
      - ./db-data/mongo/:/data/db/

  postgres:
    image: 'postgres:14.6-alpine3.17'
    restart: always
    deploy:
      mode: global
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: users
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/

